<?php

##
## Updated Moneris Payment Processing with Dynamic Configuration
##

function VerifyCard($data) {

	// Use dynamic credentials from data array, fallback to production defaults
	$store_id = isset($data['store_id']) ? $data['store_id'] : 'monca07419';
	$api_token = isset($data['api_token']) ? $data['api_token'] : 'G5F7TE7rzrM21OVzkCQD';
	$test_mode = isset($data['test_mode']) ? $data['test_mode'] : false;
	
	$type= 'card_verification';
	$cust_id= trim( $data['custid'] ); //'cust id';
	$order_id= trim( $data['orderid'] ); //'ord-'.date("dmy-G:i:s");
	$amount=number_format( $data['amount'], 2); //'1.00';
	$pan=trim( $data['cardno'] ); //'4242424242424242';
	$expiry_date=trim( $data['expdate'] ); //'2011';
	$address = isset($data["address"]) ? trim( $data["address"]) : '';
	$city = isset($data["city"]) ? trim( $data["city"] ) : '';
	$province = isset($data["province"]) ? trim( $data["province"] ) : '';
	$postal_code = trim( $data["postal_code"] );
	$postal_code = str_replace(' ', '', $postal_code);
	$cvd_value = trim ( $data["cvd"] );
	$crypt='7';
	$dynamic_descriptor='Purchase plan online Diallog.com';
	$status_check = 'false';

	error_log( "VerifyCard - Mode: " . ($test_mode ? 'TEST' : 'PRODUCTION') . ", Store: $store_id");
	error_log( "Parameters for card verification: $type, $cust_id, $order_id, $amount, $pan, $expiry_date, $crypt, $postal_code ");

	$txnArray=array('type'=>$type,
		'order_id'=>$order_id,
		'cust_id'=>$cust_id,
		'amount'=>$amount,
		'pan'=>$pan,
		'expdate'=>$expiry_date,
		'crypt_type'=>$crypt
		//'dynamic_descriptor'=>$dynamic_descriptor
		//,'wallet_indicator' => '' //Refer to documentation for details
		//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
	);

	/********************** Set Customer Information **********************/
	$avsTemplate = array(
		'avs_zipcode' => $postal_code
	);
	$mpgAvsInfo = new mpgAvsInfo ($avsTemplate);

	$cvdTemplate = array(
		'cvd_indicator' => 1,
		'cvd_value' => $cvd_value
	);
	$mpgCvdInfo = new mpgCvdInfo ($cvdTemplate);

	$mpgTxn = new mpgTransaction($txnArray);

	$mpgTxn->setCvdInfo($mpgCvdInfo);
	$mpgTxn->setAvsInfo($mpgAvsInfo);

	/****************************** Request Object *******************************/

	$mpgRequest = new mpgRequest($mpgTxn);
	$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
	$mpgRequest->setTestMode($test_mode); // Use dynamic test mode

	/***************************** HTTPS Post Object *****************************/
	$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);

	/******************************* Response ************************************/

	$mpgResponse=$mpgHttpPost->getMpgResponse();

	error_log("\nVerifyCard Response:");
	error_log("CardType = " . $mpgResponse->getCardType());
	error_log("TransAmount = " . $mpgResponse->getTransAmount());
	error_log("TxnNumber = " . $mpgResponse->getTxnNumber());
	error_log("ReceiptId = " . $mpgResponse->getReceiptId());
	error_log("TransType = " . $mpgResponse->getTransType());
	error_log("ReferenceNum = " . $mpgResponse->getReferenceNum());
	error_log("ResponseCode = " . $mpgResponse->getResponseCode());
	error_log("ISO = " . $mpgResponse->getISO());
	error_log("Message = " . $mpgResponse->getMessage());
	error_log("IsVisaDebit = " . $mpgResponse->getIsVisaDebit());
	error_log("AuthCode = " . $mpgResponse->getAuthCode());
	error_log("Complete = " . $mpgResponse->getComplete());
	error_log("TransDate = " . $mpgResponse->getTransDate());
	error_log("TransTime = " . $mpgResponse->getTransTime());
	error_log("Ticket = " . $mpgResponse->getTicket());
	error_log("TimedOut = " . $mpgResponse->getTimedOut());
	error_log("StatusCode = " . $mpgResponse->getStatusCode());
	error_log("StatusMessage = " . $mpgResponse->getStatusMessage());
	error_log("HostId = " . $mpgResponse->getHostId());
	error_log("IssuerId = " . $mpgResponse->getIssuerId());
	error_log("AVS = " .  $mpgResponse->getAvsResultCode());

	return $mpgResponse;
}

function ProcessPayment($data) {

	// Use dynamic credentials from data array, fallback to production defaults
	$store_id = isset($data['store_id']) ? $data['store_id'] : 'monca07419';
	$api_token = isset($data['api_token']) ? $data['api_token'] : 'G5F7TE7rzrM21OVzkCQD';
	$test_mode = isset($data['test_mode']) ? $data['test_mode'] : false;
	
	$type= trim( $data['type'] );//'purchase';
	$cust_id= trim( $data['custid'] ); //'cust id';
	$order_id= trim( $data['orderid'] ); //'ord-'.date("dmy-G:i:s");
	$amount=number_format( $data['amount'], 2); //'1.00';
	$pan=trim( $data['cardno'] ); //'4242424242424242';
	$expiry_date=trim( $data['expdate'] ); //'2011';
	$postal_code = trim( $data["postal_code"] );
	$cvd_value = trim ( $data["cvd"] );
	$crypt='7';
	$dynamic_descriptor='Purchase plan online Diallog.com';
	$status_check = 'false';

	error_log( "ProcessPayment - Mode: " . ($test_mode ? 'TEST' : 'PRODUCTION') . ", Store: $store_id");
	error_log( "Parameters for process payment: $type, $cust_id, $order_id, $amount, $pan, $expiry_date, $crypt, $postal_code ");

	$txnArray=array('type'=>$type,
		'order_id'=>$order_id,
		'cust_id'=>$cust_id,
		'amount'=>$amount,
		'pan'=>$pan,
		'expdate'=>$expiry_date,
		'crypt_type'=>$crypt
		//'dynamic_descriptor'=>$dynamic_descriptor
		//,'wallet_indicator' => '' //Refer to documentation for details
		//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
	);

	/********************** Set Customer Information **********************/
	$avsTemplate = array(
		'avs_zipcode' => $postal_code
	);
	$mpgAvsInfo = new mpgAvsInfo ($avsTemplate);

	$cvdTemplate = array(
		'cvd_indicator' => 1,
		'cvd_value' => $cvd_value
	);
	$mpgCvdInfo = new mpgCvdInfo ($cvdTemplate);

	$mpgTxn = new mpgTransaction($txnArray);

	$mpgTxn->setCvdInfo($mpgCvdInfo);
	$mpgTxn->setAvsInfo($mpgAvsInfo);

	/****************************** Request Object *******************************/

	$mpgRequest = new mpgRequest($mpgTxn);
	$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
	$mpgRequest->setTestMode($test_mode); // Use dynamic test mode

	/***************************** HTTPS Post Object *****************************/
	$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);

	/******************************* Response ************************************/

	$mpgResponse=$mpgHttpPost->getMpgResponse();

	error_log("\nProcessPayment Response:");
	error_log("CardType = " . $mpgResponse->getCardType());
	error_log("TransAmount = " . $mpgResponse->getTransAmount());
	error_log("TxnNumber = " . $mpgResponse->getTxnNumber());
	error_log("ReceiptId = " . $mpgResponse->getReceiptId());
	error_log("TransType = " . $mpgResponse->getTransType());
	error_log("ReferenceNum = " . $mpgResponse->getReferenceNum());
	error_log("ResponseCode = " . $mpgResponse->getResponseCode());
	error_log("ISO = " . $mpgResponse->getISO());
	error_log("Message = " . $mpgResponse->getMessage());
	error_log("IsVisaDebit = " . $mpgResponse->getIsVisaDebit());
	error_log("AuthCode = " . $mpgResponse->getAuthCode());
	error_log("Complete = " . $mpgResponse->getComplete());
	error_log("TransDate = " . $mpgResponse->getTransDate());
	error_log("TransTime = " . $mpgResponse->getTransTime());
	error_log("Ticket = " . $mpgResponse->getTicket());
	error_log("TimedOut = " . $mpgResponse->getTimedOut());
	error_log("StatusCode = " . $mpgResponse->getStatusCode());
	error_log("StatusMessage = " . $mpgResponse->getStatusMessage());
	error_log("HostId = " . $mpgResponse->getHostId());
	error_log("IssuerId = " . $mpgResponse->getIssuerId());

	return $mpgResponse;
}

